# Generated by Django 4.1.12 on 2025-02-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-date_debut"],
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="annee",
        ),
        migrations.AddField(
            model_name="education",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN COURS", "En Cours"),
                    ("TERMINER", "Terminer"),
                    ("SUPPRIMER", "Supprimer"),
                ],
                default="EN COURS",
                max_length=20,
            ),
        ),
    ]
